name: "Sync GitHub Labels"

on:
  push:
    paths:
      - ".github/ISSUE_TEMPLATE/issue-label.yml"

permissions:         # 기본 토큰 권한 설정
  issues: write      # 레이블 issues API 포함
  contents: read     # 소스 읽기

jobs:
  label-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync labels from config
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/ISSUE_TEMPLATE/issue-label.yml
